/** Known betting platforms supported on Clubkonnect. */
module.exports = [
  {
    platformId: 'nairabet',
    name: 'Nairabet',
    order: 1,
    minAmount: 100,
    maxAmount: 500000,
  },
  {
    platformId: 'bangbet',
    name: 'BangBet',
    order: 2,
    minAmount: 100,
    maxAmount: 500000,
  },
  {
    platformId: 'betway',
    name: 'BetWay',
    order: 3,
    minAmount: 100,
    maxAmount: 500000,
  },
  {
    platformId: 'betland',
    name: 'BetLand',
    order: 4,
    minAmount: 100,
    maxAmount: 500000,
  },
  {
    platformId: 'betking',
    name: 'BetKing',
    order: 5,
    minAmount: 100,
    maxAmount: 500000,
  },
  {
    platformId: '1xbet',
    name: '1xBet',
    order: 6,
    minAmount: 100,
    maxAmount: 500000,
  },
  {
    platformId: 'naijabet',
    name: 'NaijaBet',
    order: 7,
    minAmount: 100,
    maxAmount: 500000,
  },
  {
    platformId: 'sportybet',
    name: 'SportyBet',
    order: 8,
    minAmount: 100,
    maxAmount: 500000,
  },
  {
    platformId: 'merrybet',
    name: 'MerryBet',
    order: 9,
    minAmount: 100,
    maxAmount: 500000,
  },
];
