/** Betting platforms — patterns match VTpass service listings. */
module.exports = [
  {
    platformId: 'bet9ja',
    name: 'Bet9ja',
    order: 1,
    patterns: ['bet9ja', 'bet-9ja', 'bet 9ja'],
    minAmount: 100,
    maxAmount: 500000,
  },
  {
    platformId: 'sportybet',
    name: 'SportyBet',
    order: 2,
    patterns: ['sportybet', 'sporty-bet', 'sporty bet'],
    minAmount: 100,
    maxAmount: 500000,
  },
  {
    platformId: 'betking',
    name: 'BetKing',
    order: 3,
    patterns: ['betking', 'bet-king', 'bet king'],
    minAmount: 100,
    maxAmount: 500000,
  },
  {
    platformId: '1xbet',
    name: '1xBet',
    order: 4,
    patterns: ['1xbet', '1x-bet', '1x bet'],
    minAmount: 100,
    maxAmount: 500000,
  },
  {
    platformId: 'bangbet',
    name: 'BangBet',
    order: 5,
    patterns: ['bangbet', 'bang-bet', 'bang bet'],
    minAmount: 100,
    maxAmount: 500000,
  },
  {
    platformId: 'merrybet',
    name: 'MerryBet',
    order: 6,
    patterns: ['merrybet', 'merry-bet', 'merry bet'],
    minAmount: 100,
    maxAmount: 500000,
  },
  {
    platformId: 'premierbet',
    name: 'PremierBet',
    order: 7,
    patterns: ['premierbet', 'premier-bet', 'premier bet'],
    minAmount: 100,
    maxAmount: 500000,
  },
  {
    platformId: 'nairabet',
    name: 'Nairabet',
    order: 8,
    minAmount: 100,
    maxAmount: 500000,
  },
  {
    platformId: 'betway',
    name: 'BetWay',
    order: 9,
    minAmount: 100,
    maxAmount: 500000,
  },
  {
    platformId: 'betland',
    name: 'BetLand',
    order: 10,
    minAmount: 100,
    maxAmount: 500000,
  },
  {
    platformId: 'naijabet',
    name: 'NaijaBet',
    order: 11,
    minAmount: 100,
    maxAmount: 500000,
  },
];
