/** Default provider logo URLs (public brand assets). */
const PRODUCT_CDN = 'https://vtpass.com/resources/products/200X200';

module.exports = {
  DEFAULT_LOGO_URLS: {
    mtn: `${PRODUCT_CDN}/MTN-Airtime.jpg`,
    airtel: `${PRODUCT_CDN}/Airtel-Airtime.jpg`,
    glo: `${PRODUCT_CDN}/GLO-Airtime.jpg`,
    '9mobile': `${PRODUCT_CDN}/9mobile-Airtime.jpg`,
    dstv: `${PRODUCT_CDN}/DSTV.jpg`,
    gotv: `${PRODUCT_CDN}/GOTV.jpg`,
    startimes: `${PRODUCT_CDN}/Startimes.jpg`,
    waec: `${PRODUCT_CDN}/WAEC-Registration-PIN.jpg`,
    neco: `${PRODUCT_CDN}/NECO.jpg`,
    jamb: `${PRODUCT_CDN}/JAMB-PIN.jpg`,
    bet9ja: 'https://www.bet9ja.com/favicon.ico',
    sportybet: 'https://www.sportybet.com/favicon.ico',
    betking: 'https://www.betking.com/favicon.ico',
    '1xbet': 'https://1xbet.ng/favicon.ico',
    bangbet: 'https://www.bangbet.com/favicon.ico',
    merrybet: 'https://merrybet.com/favicon.ico',
    premierbet: 'https://www.premierbet.com/favicon.ico',
    ikeja: `${PRODUCT_CDN}/Ikeja-Electric.jpg`,
    eko: `${PRODUCT_CDN}/Eko-Electric.jpg`,
    abuja: `${PRODUCT_CDN}/Abuja-Electric.jpg`,
    kaduna: `${PRODUCT_CDN}/Kaduna-Electric.jpg`,
    kano: `${PRODUCT_CDN}/Kano-Electric.jpg`,
    portharcourt: `${PRODUCT_CDN}/Port-Harcourt-Electric.jpg`,
    jos: `${PRODUCT_CDN}/Jos-Electric.jpg`,
    ibadan: `${PRODUCT_CDN}/Ibadan-Electric.jpg`,
  },
  DEFAULT_PROVIDERS: [
    { providerId: 'mtn', name: 'MTN', category: 'network', order: 1 },
    { providerId: 'airtel', name: 'Airtel', category: 'network', order: 2 },
    { providerId: 'glo', name: 'Glo', category: 'network', order: 3 },
    { providerId: '9mobile', name: '9mobile', category: 'network', order: 4 },
    { providerId: 'dstv', name: 'DStv', category: 'tv', order: 1 },
    { providerId: 'gotv', name: 'GOtv', category: 'tv', order: 2 },
    { providerId: 'startimes', name: 'StarTimes', category: 'tv', order: 3 },
    { providerId: 'waec', name: 'WAEC', category: 'education', order: 1 },
    { providerId: 'neco', name: 'NECO', category: 'education', order: 2 },
    { providerId: 'jamb', name: 'JAMB', category: 'education', order: 3 },
    { providerId: 'bet9ja', name: 'Bet9ja', category: 'betting', order: 1 },
    { providerId: 'sportybet', name: 'SportyBet', category: 'betting', order: 2 },
    { providerId: 'betking', name: 'BetKing', category: 'betting', order: 3 },
    { providerId: '1xbet', name: '1xBet', category: 'betting', order: 4 },
    { providerId: 'bangbet', name: 'BangBet', category: 'betting', order: 5 },
    { providerId: 'merrybet', name: 'MerryBet', category: 'betting', order: 6 },
    { providerId: 'premierbet', name: 'PremierBet', category: 'betting', order: 7 },
    { providerId: 'ikeja', name: 'Ikeja Electric', category: 'electricity', order: 1 },
    { providerId: 'eko', name: 'Eko Electric', category: 'electricity', order: 2 },
    { providerId: 'abuja', name: 'Abuja Electric', category: 'electricity', order: 3 },
    { providerId: 'kaduna', name: 'Kaduna Electric', category: 'electricity', order: 4 },
    { providerId: 'kano', name: 'Kano Electric', category: 'electricity', order: 5 },
    { providerId: 'portharcourt', name: 'PHED', category: 'electricity', order: 6 },
    { providerId: 'jos', name: 'Jos Electric', category: 'electricity', order: 7 },
    { providerId: 'ibadan', name: 'Ibadan Electric', category: 'electricity', order: 8 },
  ],
};
